language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
install: yarn install
before_script:
- yarn add grunt-cli -g
- openssl aes-256-cbc -K $encrypted_147a9dc5f750_key -iv $encrypted_147a9dc5f750_iv
  -in test.json.enc -out test.json -d
script: yarn run test


